FROM openjdk:11-jdk-slim-buster
WORKDIR /simianchecker/
COPY pom.xml /simianchecker/
COPY src /simianchecker/src/
COPY mvnw /simianchecker/
COPY .mvn /simianchecker/.mvn/
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait /simianchecker/wait
RUN chmod +x /simianchecker/wait
RUN chmod +x /simianchecker/mvnw
