version: '3.9'

services:

  database:
    image: mongo
    volumes:
      - "~/mongo/data:/data/db"
    ports:
      - "27017:27017"

  web:
    build:
      context: .
      dockerfile: Dockerfile-test
    container_name: "simian-checker-app-test"
    environment:
      - WAIT_HOSTS=database:27017
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - MONGODB_HOST=database
      - MONGODB_PORT=27017
    ports:
      - "8082:8082"
    depends_on:
      - database
    command: sh -c "/simianchecker/wait && /simianchecker/mvnw clean test"

