version: '2.3'

services:
        mongo:
                image: mongo
                restart: always

        web:
                build: .
                ports:
                - "8082:8082"
                links:
                - mongo
