version: '3'

services:

  database:
    image: mongo
    volumes:
      - "~/mongo/data:/data/db"
    ports:
      - "27017:27017"
    restart: unless-stopped

  web:
    build: .
    container_name: "simian-checker-app"
    environment:
      - WAIT_HOSTS=database:27017
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - MONGODB_HOST=database
      - MONGODB_PORT=27017
    ports:
      - "8082:8082"
    depends_on:
      - database
    restart: unless-stopped
    command: sh -c "/simianchecker/wait && java -jar /simianchecker/app.jar"

